package com.daydaynote;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.daydaynote.entity.NoteConsumeMsg;

import com.daydaynote.NoteConsumeMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteConsumeMsgDaoConfig;

    private final NoteConsumeMsgDao noteConsumeMsgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteConsumeMsgDaoConfig = daoConfigMap.get(NoteConsumeMsgDao.class).clone();
        noteConsumeMsgDaoConfig.initIdentityScope(type);

        noteConsumeMsgDao = new NoteConsumeMsgDao(noteConsumeMsgDaoConfig, this);

        registerDao(NoteConsumeMsg.class, noteConsumeMsgDao);
    }
    
    public void clear() {
        noteConsumeMsgDaoConfig.clearIdentityScope();
    }

    public NoteConsumeMsgDao getNoteConsumeMsgDao() {
        return noteConsumeMsgDao;
    }

}
